### PR TITLE
Correct few typos and add hyperlink for users to email

### PR DESCRIPTION
**Pull request by SudharakaP**
Resolve https://github.com/opencollective/opencollective/issues/5072

image

image

### CODE REVIEW

**Review by znarf — APPROVED** [review]
I'm wondering if opening the contact form would be a better option.

But that's fine for me and ok to merge.

**Comment by SudharakaP** [comment]
> I'm wondering if opening the contact form would be a better option.
> 
> But that's fine for me and ok to merge.

Yeah, that's better I think we use the contact form elsewhere. There's two places we use this email and I've changed them both to use the contact form instead. Also I noticed that the modal has a slight formatting problem with the width and height; 

image

Which was corrected by slightly increasing the width and height. 

image

If no objections I'll be merging this one.

**Comment by kaylarep** [comment]
just want to say again, as a platform user/host admin, i really do not love the contact modal. there's not a way to track submitted messages, plus I'm pretty unclear about exactly where these messages arrive to/how many people & who receives them.  I always prefer to be directly messaged to contact@opencollective.foundation or my distinct email because it creates a trail i can keep track of.

at the very least there needs to be an option to 'email me a copy' at the bottom of the modal.

**Comment by SudharakaP** [comment]
> just want to say again, as a platform user/host admin, i really do not love the contact modal. there's not a way to track submitted messages, plus I'm pretty unclear about exactly where these messages arrive to/how many people & who receives them. I always prefer to be directly messaged to [contact@opencollective.foundation](mailto:contact@opencollective.foundation) or my distinct email because it creates a trail i can keep track of.
> 
> at the very least there needs to be an option to 'email me a copy' at the bottom of the modal.

@kaylarep : I checked and it seems that the modal also submits the messages to `contact@opencollective.foundation`. Yes I think we could add a `email me a copy` at the bottom of the modal. 

@zanrf: You okay with adding this `email me a copy` option so that the user gets a copy? Alternatively we could use the `mailto:<email-address>` links as we did before but I think it's nice if we can keep things consistent and change all the `Contact Us` links to `mailto:<email-address>` links. 🤔

**Pull request merged**
