### PR TITLE
Updates to language

### PR DESCRIPTION
**Pull request by natehn**
Includes minor adjustments to language and updated links to the current OCF documentation, plus an update to the copyright year

### CODE REVIEW

**Comment by natehn** [comment]
I don't have a ton of experience with html, so please double-check my work! :)

**Comment by SudharakaP** [comment]
@znarf : Very strange PR. There's no changes here and there's 0 commits. 🤔 🤔

**Comment by natehn** [comment]
@SudharakaP probably because I don't know what I'm doing! :)

**Comment by SudharakaP** [comment]
@natehn : Not to worry, thanks for the contribution. You can check whether your changes are there by going the [preview url above](https://github.com/opencollective/foundation-website/pull/11#issuecomment-805442936). For this PR it's, https://foundation-website-git-fork-natehn-master-opencollective.vercel.app. If they are not there, I would suggest opening a new PR. 😄

**Comment by natehn** [comment]
@SudharakaP the changes went through on the live site, so I think we're good

**Comment by SudharakaP** [comment]
> @SudharakaP the changes went through on the live site, so I think we're good

Great. Think it maybe a github issue. 🤔

**Pull request merged**
